Implement a Modyn Client gRPC component
eth-easl/modyn pull request #333
Opened 2023-11-15 21:40 UTC by jenny011

This PR implements the modyn client part of #317.
1. Add a modynclient/ on the same level as modyn/.

TODOs
1. Add GetPipelineStatus to supervisor grpc proto
2. Implement enlighten and maybe tensorboard.
4. Unit tests
5. Integration tests

2023-12-13 14:04 UTC, MaxiBoether requested changes
Thank you! This already looks very good. My main point was the question whether we can clean up the messages a little bit by using enums/StrEnums instead of hardcoding strings.

Additionally, there are some debug-ish log messages that either need to go to logger.debug or be more complete sentences :) And my last question is about some open TODOs/things, since some things are apparently still open. Do you plan to make a clean up PR on #329 that solves these things?

2023-12-18 22:59 UTC, jenny011 commented on modyn/supervisor/internal/pipeline_executor/pipeline_executor.py
> +            # TODO(#317): ??? what is it ???
removed

2023-12-18 22:59 UTC, jenny011 commented on modyn/supervisor/internal/supervisor.py
> +        logger.info(f"Validate system: dataset {dataset_available}, trainer server {trainer_server_available}")
done

2023-12-18 22:59 UTC, jenny011 commented on modyn/supervisor/internal/supervisor.py
> +            ret["pipeline_stage"] = [msg]
Updated. All the top-level msgs are "repeated" fields, so they should be lists containing submsgs.

2023-12-18 22:59 UTC, jenny011 commented on modyn/supervisor/internal/utils/pipeline_info.py
> +    def get_pipeline_stage(self, timeout: float = QUEUE_GET_TIMEOUT) -> Optional[dict]:
done

2023-12-18 22:59 UTC, jenny011 commented on modyn/supervisor/internal/supervisor.py
> +            return {"pipeline_id": -1, "exception": "Failed to register pipeline"}
It is to keep the supervisor running instead of killing it on exception. The error message is sent to the client.

2023-12-18 22:59 UTC, jenny011 commented on modynclient/client/internal/grpc_handler.py
> +# TODO(#317 client): share with modyn or make a copy?
done. Three TODO#317s remains to be addressed in future issues/PRs.

2023-12-18 22:59 UTC, jenny011 commented on modynclient/config/examples/modyn_client_config_container.yaml
> +project:
"modyn_client_config" is for clients on the host machine and "modyn_client_config_container" is for clients in a container. The only difference at the moment is the supervisor ip/hostname.

2023-12-18 22:59 UTC, jenny011 commented on modynclient/tests/client/internal/utils/test_training_status_tracker.py
> +# TODO(#317): move these to modynclient
It's a leftover. Removed.

2023-12-18 22:59 UTC, jenny011 commented on modyn/supervisor/internal/grpc/supervisor_grpc_servicer.py
> +        logger.info(f"[{pid}][{tid}]: pipeline config {pipeline_config}")
done

2023-12-18 22:59 UTC, jenny011 commented on modyn/supervisor/internal/grpc_handler.py
> +        logger.info("wait for training completion")
done

2023-12-18 22:59 UTC, jenny011 commented on modyn/supervisor/internal/grpc_handler.py
> +        logger.info("wait for evaluation completion")
done

2023-12-18 22:59 UTC, jenny011 commented on modyn/supervisor/internal/supervisor.py
> +                    pipeline_stage = p_info.get_pipeline_stage()
done

2023-12-18 23:02 UTC, jenny011 commented on modyn/supervisor/internal/grpc_handler.py
> +                "stage": "Waiting for training",
done

2023-12-18 23:02 UTC, jenny011 commented on modyn/supervisor/internal/grpc_handler.py
> +                "msg_type": "id",
done

2023-12-18 23:02 UTC, jenny011 commented on modyn/supervisor/internal/grpc_handler.py
> +                "id_msg": {"id_type": "training", "id": training_id},
done

2024-01-05 14:57 UTC, merged