Updated storage and training files to enable text generation tasks. A…
eth-easl/modyn pull request #640
Opened 2024-12-11 16:13 UTC by sjohn4

Made minor updates to the environment and ensured everything passes the standard Python compliance tests, maintaining compatibility with Modyn's existing functionality. Added GPT-2 as a model that can be used along with the GPT-2 tokenizer. Introduced the generative flag to the Modyn pipeline, enabling it to distinguish between generative and classification tasks. Also updated some Python test files to incorporate this flag, ensuring no errors are thrown.

2024-12-13 14:47 UTC, MaxiBoether requested changes
I briefly skimmed the PR. Thanks for the work! The biggest feedback right now would be that we should not have parallel codepaths which are mostly copy/paste of existing ones but without labels. Rather, let's have clean code where we move labels to be optional, both in the c++/protobuf/python worlds. And before I do the proper review, would be great if you could check the diff for changes that should not go onto main :)

Thanks!

2024-12-13 14:47 UTC, MaxiBoether commented on modyn/config/examples/modyn_config.yaml
> +  ignore_existing_trigger_samples: true
let's not merge this

2024-12-13 14:47 UTC, MaxiBoether commented on modyn/trainer_server/internal/dataset/online_dataset.py
> +    def _fetch_partition_noprefetch_generative(  # based on the one above
similar comments here. I would propose to refactor the PR such that we don't have parallel codepaths for generative

2025-01-06 14:41 UTC, closed without merging

2025-01-06 14:41 UTC, sjohn4 commented
Redid most of this changes, this pr is not relevant anymore, I will open a new one shortly.